version: '2'
services:

  ldap:
    build: ldap/
    container_name: ldap
    hostname: ldap
    ports:
     - "389:389"
    networks:
     - schoolconnect
    env_file:
     - ./settings.env

  php_ldap_admin:
    build: php_ldap_admin/
    links:
     - "ldap:ldap.schoolconnect"
    ports:
     - "89:80"
    container_name: php_ldap_admin
    hostname: php_ldap_admin
    # 'dpkg-reconfigure slapd' hangs when a domain with an underscore _ is used
    # (which is unfortunately docker-compose default behavior)
    # so an alias is necessary if no custom (separately started) network shall be uses:
    networks:
     - schoolconnect
    env_file:
     - ./settings.env
    volumes:
      - schoolconnect_admin_mysql:/var/lib/phpldap

  samba:
    build: samba/
    links:
     - "ldap:ldap.schoolconnect"
    container_name: samba
    hostname: samba
    ports:
     - "137:137"
     - "138:138"
     - "139:139"
    networks:
     - schoolconnect
    env_file:
     - ./settings.env
    volumes:
     - ./mount/samba:/home

  schoolconnect_admin:
    build: schoolconnect_admin/
    links:
     - "ldap:ldap.schoolconnect"
     - "samba:samba.schoolconnect"
    ports:
     - "84:80"
     - "447:443"
    container_name: schoolconnect_admin
    hostname: schoolconnect_admin
    networks:
     - schoolconnect
    env_file:
     - ./settings.env
    volumes:
#      - /home/dirk/Schule/IT/PhilleConnect/docker/var/admin_mysql/:/var/lib/mysql/
      - schoolconnect_admin_mysql:/var/lib/mysql/
      - schoolconnect_admin_config:/var/www/html/config/

volumes:
  schoolconnect_admin_mysql:
  schoolconnect_admin_config:
  schoolconnect_ldap:

networks:
  schoolconnect:
