version: '2'
services:

  ldap:
    build: ldap/
    #image: philleconnect/ldap:latest
    container_name: ldap
    hostname: ldap
    restart: always
    ports:
      - "389:389"
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      - philleconnect_ldap_db:/var/lib/ldap

  php_ldap_admin:
    build: php_ldap_admin/
    #image: philleconnect/php_ldap_admin:latest
    restart: always
    links:
      - "ldap"
    ports:
      - "89:80"
    container_name: php_ldap_admin
    hostname: php_ldap_admin
    # 'dpkg-reconfigure slapd' hangs when a domain with an underscore _ is used
    # (which is unfortunately docker-compose default behavior)
    # so an alias is necessary if no custom (separately started) network shall be used:
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      - philleconnect_admin_mysql:/var/lib/phpldap

  samba:
    build: samba/
    #image: philleconnect/samba:latest
    restart: always
    container_name: samba
    hostname: samba
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      - ./mount/samba:/home

  pc_admin:
    build: pc_admin/
    #image: philleconnect/pc_admin:latest
    restart: always
    ports:
      - "84:80"
      - "447:443"
    container_name: pc_admin
    hostname: pc_admin
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      # don't make tailing slashes in volumes!!!
      - philleconnect_admin_mysql:/var/lib/mysql
      - philleconnect_admin_config:/var/www/html/config
      - ./mount/samba:/home

volumes:
  philleconnect_admin_mysql:
  philleconnect_admin_config:
  philleconnect_ldap_db:

networks:
  philleconnect:
