version: '2'
services:

  ldap:
    build: ldap/
    #image: philleconnect/ldap:latest
    container_name: ldap
    hostname: ldap
    restart: always
    ports:
      - "389:389"
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      - philleconnect_ldap_db:/var/lib/ldap

  samba:
    build: samba/
    #image: philleconnect/samba:latest
    restart: always
    container_name: samba
    hostname: samba
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
      - ./mount/samba:/home

  pc_admin:
    build: pc_admin/
    #image: philleconnect/pc_admin:latest
    restart: always
    ports:
      - "84:80"
      - "447:443"
    container_name: pc_admin
    hostname: pc_admin
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    volumes:
#      - /home/dirk/Schule/IT/PhilleConnect/docker/var/admin_mysql/:/var/lib/mysql/
      # don't make tailing slashes in volumes!!!
      - philleconnect_admin_mysql:/var/lib/mysql
      - philleconnect_admin_config:/var/www/html/config
      - ./mount/samba:/home

volumes:
  philleconnect_admin_mysql:
  philleconnect_admin_config:
  philleconnect_ldap_db:

networks:
  philleconnect:
